
services:
  # Serviço da API FastAPI
  higiplas_api:
    build:
      context: ./backend  # 1. CONTEXTO: Diz ao Docker para "entrar" nesta pasta primeiro.
      dockerfile: Dockerfile     # 2. DOCKERFILE: O nome do arquivo a ser usado.
    command: /bin/sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
      - ./backend/app:/code/app # Mapeia o código para desenvolvimento
    env_file:
      - .env
    depends_on:
      - higiplas_postgres
    networks:
      - higiplas_network
    

  # Serviço do Banco de Dados PostgreSQL
  # Porta 5433 no host para não conflitar com PostgreSQL instalado na máquina (5432)
  higiplas_postgres:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    networks:
      - higiplas_network
    env_file:
      - ./.env # Carrega as variáveis de ambiente do seu arquivo .env
    restart: unless-stopped

  higiplas_frontend:
    build:
      context: ./higiplas_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - higiplas_api
    networks:
      - higiplas_network

volumes:
  postgres_data: {}
       

networks:
  higiplas_network:
    driver: bridge